apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::675767036124:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-L3JNGBUG745S
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-15T06:20:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1612"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3ab000fd-dbc4-4630-821e-e9147c6ccc6c
